---
- name: Install choco
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

- name: Install choco packages
  include_tasks: install-choco-packages.yml
